version: '3'
services:
  app:
    container_name: image-carousel
    build: .
    ports:
      - '80:3031'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'